#![deny(unsafe_code)]

use eyre::Result;
use std::error::Error;

pub async fn liquidations() -> Result<(), Box<dyn Error>> {
    Ok(())
}
